//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_administrador
    {
        public int id_administrador { get; set; }
        public string ds_email { get; set; }
        public string ds_login { get; set; }
        public string ds_senha { get; set; }
        public string ds_nivel_de_acesso { get; set; }
    }
}
