//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_compra
    {
        public int id_compra { get; set; }
        public System.DateTime dt_compra { get; set; }
        public Nullable<int> id_cliente { get; set; }
    }
}
