//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_cliente
    {
        public int id_cliente { get; set; }
        public string cd_cpf { get; set; }
        public string nm_cliente { get; set; }
        public Nullable<System.DateTime> dt_nascimento { get; set; }
        public string ds_nivel_de_acesso { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public string email { get; set; }
        public string nm_celular { get; set; }
        public string nm_telefone { get; set; }
        public string cartao_de_credito { get; set; }
        public string ativo { get; set; }
        public Nullable<int> id_endereco { get; set; }
    }
}
