//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produto
    {
        public int id_produto { get; set; }
        public string nm_produto { get; set; }
        public string ds_produto { get; set; }
        public string nm_marca { get; set; }
        public decimal vl_preco { get; set; }
        public decimal vl_preco_promocional { get; set; }
        public int qt_produto { get; set; }
        public Nullable<decimal> ds_peso { get; set; }
        public Nullable<sbyte> ds_ativo { get; set; }
        public Nullable<System.DateTime> dt_validade { get; set; }
        public string image1 { get; set; }
        public string image2 { get; set; }
        public string image3 { get; set; }
        public Nullable<int> id_categoria { get; set; }
    }
}
